export const symptomToCondition = {
    "Fever": ["Flu", "COVID-19", "Common Cold"],
    "Cough": ["Bronchitis", "Pneumonia", "Asthma"],
    "Headache": ["Migraine", "Tension Headache", "Sinusitis"],
    "Fatigue": ["Anemia", "Chronic Fatigue Syndrome", "Depression"],
    "Sore Throat": ["Strep Throat", "Viral Pharyngitis", "Allergies"],
    "Nausea": ["Gastroenteritis", "Pregnancy", "Food Poisoning"],
    "Diarrhea": ["Irritable Bowel Syndrome", "Infection", "Food Allergy"],
    "Chest Pain": ["Heart Attack", "Angina", "Heartburn"],
    "Shortness of Breath": ["Asthma", "COPD", "Pneumonia"],
    "Rash": ["Allergic Reaction", "Eczema", "Psoriasis"],
    "Joint Pain": ["Arthritis", "Bursitis", "Gout"],
    "Dizziness": ["Vertigo", "Dehydration", "Low Blood Sugar"],
    "Abdominal Pain": ["Appendicitis", "Gastritis", "Irritable Bowel Syndrome"],
    "Swelling": ["Edema", "Injury", "Infection"],
    "Numbness": ["Neuropathy", "Stroke", "Multiple Sclerosis"],
    "Blurred Vision": ["Refractive Errors", "Cataracts", "Glaucoma"],
    "Earache": ["Ear Infection", "Eustachian Tube Dysfunction", "TMJ Disorder"],
    "Itching": ["Allergic Reaction", "Eczema", "Scabies"],
    "Loss of Appetite": ["Depression", "Chronic Illness", "Gastrointestinal Disorders"],
    "Weight Loss": ["Cancer", "Diabetes", "Thyroid Disorders"]
  };
  
export const conditionToSpecialist = {
    "Flu": ["Pediatrics", "General Physician"],
    "COVID-19": ["Pediatrics", "General Physician"],
    "Common Cold": ["Pediatrics", "General Physician"],
    "Bronchitis": ["Pediatrics", "General Physician"],
    "Pneumonia": ["Pediatrics", "General Physician"],
    "Asthma": ["Pediatrics", "General Physician"],
    "Migraine": ["Neurology", "General Physician"],
    "Tension Headache": ["Neurology", "General Physician"],
    "Sinusitis": ["ENT", "General Physician"],
    "Anemia": ["Pediatrics", "General Physician"],
    "Chronic Fatigue Syndrome": ["Neurology", "General Physician"],
    "Depression": ["Neurology", "General Physician"],
    "Strep Throat": ["Pediatrics", "General Physician"],
    "Viral Pharyngitis": ["Pediatrics", "General Physician"],
    "Allergies": ["ENT", "General Physician"],
    "Gastroenteritis": ["Pediatrics", "General Physician"],
    "Pregnancy": ["Pediatrics", "General Physician"],
    "Food Poisoning": ["Pediatrics", "General Physician"],
    "Irritable Bowel Syndrome": ["Pediatrics", "General Physician"],
    "Infection": ["Pediatrics", "General Physician"],
    "Food Allergy": ["Pediatrics", "General Physician"],
    "Heart Attack": ["Cardiology", "General Physician"],
    "Angina": ["Cardiology", "General Physician"],
    "Heartburn": ["Cardiology", "General Physician"],
    "COPD": ["Cardiology", "General Physician"],
    "Allergic Reaction": ["Dermatology", "General Physician"],
    "Eczema": ["Dermatology", "General Physician"],
    "Psoriasis": ["Dermatology", "General Physician"],
    "Arthritis": ["Orthopedics", "General Physician"],
    "Bursitis": ["Orthopedics", "General Physician"],
    "Gout": ["Orthopedics", "General Physician"],
    "Vertigo": ["Neurology", "General Physician"],
    "Dehydration": ["Neurology", "General Physician"],
    "Low Blood Sugar": ["Neurology", "General Physician"],
    "Appendicitis": ["Pediatrics", "General Physician"],
    "Gastritis": ["Pediatrics", "General Physician"],
    "Edema": ["Orthopedics", "General Physician"],
    "Injury": ["Orthopedics", "General Physician"],
    "Neuropathy": ["Neurology", "General Physician"],
    "Stroke": ["Neurology", "General Physician"],
    "Multiple Sclerosis": ["Neurology", "General Physician"],
    "Refractive Errors": ["Neurology", "General Physician"],
    "Cataracts": ["Neurology", "General Physician"],
    "Glaucoma": ["Neurology", "General Physician"],
    "Ear Infection": ["ENT", "General Physician"],
    "Eustachian Tube Dysfunction": ["ENT", "General Physician"],
    "TMJ Disorder": ["ENT", "General Physician"],
    "Scabies": ["Dermatology", "General Physician"],
    "Diabetes": ["Pediatrics", "General Physician"],
    "Thyroid Disorders": ["Pediatrics", "General Physician"]
};
